name: Execução E2E Testes

on:
  workflow_call:
    inputs:
      java_version:
        required: false
        default: 18
        type: number
      maven_version:
        required: false
        default: "3.9.4"
        type: string
      folder_allure:
        required: false
        default: "target/allure-results"
        type: string
    secrets:
      git_token:
        required: true

jobs:
  mvn-run:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Maven
        uses: s4u/setup-maven-action@v1.8.0
        with:
          java-version: ${{ inputs.java_version }}
          maven-version: ${{ inputs.maven_version }}

      - name: Run tests
        run: mvn clean install

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: ${{ inputs.folder_allure }}
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.git_token }}
          publish_branch: gh-pages
          publish_dir: allure-history
