name : Execução E2E

on:
  workflow_call:
    inputs :
     java_version:
      required: false
      default: 17
      type : number
     maven_version:
      required: true
      default: 3.9.8
      type : string
     folder_allure:
      required: true
      default: "target/allure_results"
      type : string


    secrets :
     git_token:
       required: true



jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: ${{ inputs.java_version}}
          maven-version: ${{ inputs.maven_version}}

      - name: Execute e2e tests
        run: mvn clean install

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: ${{ inputs.folder_allure}}
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always  ()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.git_token }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
